all: memory-user null offbyone

memory-user: memory-user.c
	gcc -Wall -g -o memory-user memory-user.c

null: null.c
	gcc -Wall -g -o null null.c

offbyone: offbyone.c
	gcc -Wall -g -o offbyone offbyone.c

clean:
	rm -f memory-user null offbyone
