all: myfirst mysecond mythird myfourth

myfirst: myfirst.c
	gcc -Wall -g -pthread -o myfirst myfirst.c

mysecond: mysecond.c
	gcc -Wall -g -pthread -o mysecond mysecond.c

mythird: mythird.c
	gcc -Wall -g -pthread -o mythird mythird.c

myfourth: myfourth.c
	gcc -Wall -g -pthread -o myfourth myfourth.c

clean:
	rm -f myfirst mysecond mythird myfourth
